//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDC.Dominio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int IdCarrinho { get; set; }
        public System.DateTime DataHora { get; set; }
        public int ItensCarrinho { get; set; }
    
        public virtual ItemCarrinho ItemCarrinho { get; set; }
    }
}
