//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDC.Dominio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCarrinho
    {
        public ItemCarrinho()
        {
            this.Carrinho = new HashSet<Carrinho>();
        }
    
        public int IdItemCarrinho { get; set; }
        public int Produtos { get; set; }
        public int Quantidade { get; set; }
    
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
