//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDC.Dominio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ItemCarrinho = new HashSet<ItemCarrinho>();
        }
    
        public int IdProduto { get; set; }
        public string Descricao { get; set; }
        public string Imagem { get; set; }
        public string Nome { get; set; }
        public int Peso { get; set; }
        public decimal Preco { get; set; }
        public int Tipo { get; set; }
    
        public virtual ICollection<ItemCarrinho> ItemCarrinho { get; set; }
        public virtual TipodeProduto TipodeProduto { get; set; }
    }
}
