//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDC.Dominio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDCEntities : DbContext
    {
        public CDCEntities()
            : base("name=CDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrinho> Carrinho { get; set; }
        public virtual DbSet<ItemCarrinho> ItemCarrinho { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<TipodeProduto> TipodeProduto { get; set; }
    }
}
